title: My Portfolio
description: Find my research and projects below
theme: minima
baseurl: "" # Leave empty if hosting at the root, e.g., username.github.io
url: "https://julieta7312.github.io/" # Replace with your site URL